async function api(u,o={}){let r=await fetch(u,o);if(r.status==401){location='login.html';return null}return r.json()}
async function session(){let d=await api('api/session.php');if(!d||!d.logged_in)return location='login.html';who.textContent=d.user.full_name+' | '+d.user.role}
function show(x){document.querySelectorAll('main section').forEach(s=>s.classList.add('hide'));document.getElementById(x).classList.remove('hide');if(x==='dashboard')dash();if(x==='employees')employees();if(x==='projects')projects();if(x==='tasks')tasks()}
async function dash(){let d=await api('api/dashboard.php');ec.textContent=d.employees;pc.textContent=d.projects;tc.textContent=d.tasks;cc.textContent=d.completed_tasks}
async function employees(){let d=await api('api/employees.php');et.innerHTML=d.map(x=>`<tr><td>${x.employee_id}</td><td>${x.name}</td><td>${x.position}</td><td>${x.department}</td><td><button class=danger onclick="del('employees.php',${x.employee_id})">Delete</button></td></tr>`).join('');te.innerHTML=d.map(x=>`<option value=${x.employee_id}>${x.name}</option>`).join('')}
async function projects(){let d=await api('api/projects.php');pt.innerHTML=d.map(x=>`<tr><td>${x.project_id}</td><td>${x.project_name}</td><td>${x.manager}</td><td>${x.deadline}</td><td>${x.status}</td><td><button class=danger onclick="del('projects.php',${x.project_id})">Delete</button></td></tr>`).join('');tp.innerHTML=d.map(x=>`<option value=${x.project_id}>${x.project_name}</option>`).join('')}
async function tasks(){let d=await api('api/tasks.php');tt.innerHTML=d.map(x=>`<tr><td>${x.task_id}</td><td>${x.task_name}</td><td>${x.employee}</td><td>${x.project}</td><td>${x.priority}</td><td>${x.status}</td><td><button class=danger onclick="del('tasks.php',${x.task_id})">Delete</button></td></tr>`).join('')}
async function post(url,data){await api('api/'+url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});dash()}
ef.onsubmit=e=>{e.preventDefault();post('employees.php',{name:en.value,position:ep.value,department:ed.value}).then(employees)};pf.onsubmit=e=>{e.preventDefault();post('projects.php',{project_name:pn.value,manager:pm.value,deadline:pd.value,status:ps.value}).then(projects)};tf.onsubmit=e=>{e.preventDefault();post('tasks.php',{task_name:tn.value,employee_id:te.value,project_id:tp.value,priority:ti.value,status:ts.value}).then(tasks)};
async function del(file,id){if(confirm('Delete this record?')){await api('api/'+file+'?id='+id,{method:'DELETE'});dash();employees();projects();tasks()}}async function logout(){await api('api/logout.php',{method:'POST'});location='login.html'}session().then(()=>show('dashboard'));